# optimizer parameters
# gaussians
iterations: 50_000
position_lr_init: 0.00016
position_lr_final: 0.0000016
position_lr_delay_mult: 0.01
position_lr_max_steps: 30_000
feature_lr: 0.0025
feature_lr_final: 0.000025
opacity_lr: 0.05
scaling_lr: 0.001
rotation_lr: 0.001
percent_dense: 0.01
lambda_dssim: 0.2
densification_interval: 500 # 100, 1000
opacity_reset_interval: 3000
densify_from_iter: 500
densify_until_iter: 15_000
densify_grad_threshold: 0.0001 # 0.0002
normal_lr: 0.0002
specular_lr: 0.0002
roughness_lr: 0.0002
metalness_lr: 0.0002
albedo_lr: 0.0002
reg_normal_from_iter: 15_000 
normal_reg_until_iter: 0 # 30_000
lambda_dist: 0 #1, 10
lambda_normal: 0.05 # 1e-1 #2e-1
reg_depth_from_iter: 15_000
lambda_depth : 0.5 #0.5 # 0.05
lambda_depth_smooth: 0.05 # 0.05
lambda_delta_reg: 1e-3
lambda_scale: 100.0
# l1 loss type
l1_loss_type: None # "sky_pixels_weight", "sky_fixed_weight"
# environment light 
envlight_sh_lr: 0.0002
envlight_sh_wd: 0
lambda_envlight: 0.05
lambda_envlight_sh_prior: 0
envlight_prior_until_iter: 0
envlight_loss_until_iter: 50_000
# per-image embeddings
embeddings_lr: 0.0002
embednet_pretrain_epochs: 100
optim_embeddings_test_iters: 100