# model parameters
envlight_sh_degree: 4
sky_sh_degree: 1
init_embeddings: True
init_sh_mlp: True
embeddings_dim: 32
load_iteration: None
fix_sky: False
defaults:
  - optimizer: optimization_params.yaml
  - pipe: pipeline_params.yaml
  - dataset: dataset_params.yaml