# model parameters
envlight_sh_degree: 4
init_embeddings: True
init_sh_mlp: True
embeddings_dim: 32
num_sky_points: 10000
load_iteration: None
defaults:
  - optimizer: optimization_params.yaml
  - pipe: pipeline_params.yaml
  - dataset: dataset_params.yaml